### ISSUE TITLE
Git problems

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#95]
While testing `git` on managarm, the following unimplemented functions are observed

- [x] `pthread_setcancelstate()`, required for most of the operations, including `git commit` and `git log`
- [x] `rmdir()`, required for `git checkout`, possibly only when directories need to be removed (see issue #50).
- [x] `utime()`, required for `git add`, this is implemented for managarm, but calls it with unsupported modes (meaning one of the fields is not `UTIME_NOW`).
- [x] with `git add` working(ish), `git commit` now throws an `SIGSEGV` in an internal mlibc header, before triggering the `pthread_setcancelstate()` function. This problem is tracked in a seperate issue, issue #111 
- [x] fetching repo's with either `git clone`, `git pull` or `git fetch` (assuming git:// repo's) require handling of the `/etc/services` file to work (part of issue #99)
- [x] fetching, cloning or pulling repo's (http(s):// repo's) require `curl` (tracked in managarm/bootstrap-managarm#33)

This is a tracking issue for all `git` related problems in `mlibc`
